### ISSUE TITLE
Can't not setup algolia cli in Github action step.

### ISSUE THREAD

**Issue by elkan1788** [algolia/setup-algolia-cli#1]
Hi guys:

I were following the `README` content and add algolia cli step in my Github action, but so sad that not working as well, then throws and exception out like this:

```
Run algolia/setup-algolia-cli@v1.0.0
  with:
    version: latest
  env:
    ALGOLIA_APPLICATION_ID: ***
    ALGOLIA_ADMIN_API_KEY: ***
Object prototype may only be an Object or null: undefined
Waiting 1[2](https://github.com/elkan1788/myblog-sources/actions/runs/3180191868/jobs/5183480429#step:7:2) seconds before trying again
Object prototype may only be an Object or null: undefined
Waiting 1[4](https://github.com/elkan1788/myblog-sources/actions/runs/3180191868/jobs/5183480429#step:7:4) seconds before trying again
Error: TypeError: Object prototype may only be an Object or null: undefined
```

How fix this issue, thanks.

**Comment by clemfromspace** [comment]
Hi @elkan1788 and sorry for the late reply.
Regarding your issue, we had an error for the default version to install, I just pushed a change that should solve the issue: ecd8ce364b0b18dda462fd3edfa94d0c7da17838

**Comment by northern-mindset** [comment]
Why wouldn't you create a new release with this change? I just faced this issue with `uses: algolia/setup-algolia-cli@v1.0.0`. I saw you changed the README to refer to the `master`, but I believe many developers including me prefer to pin actions to a specific version (full or major) rather than use `master`. Please consider adding a new release and maybe ever-up-to-date `v1` and `v1.0` tags as well.

Relevant links:

- https://github.com/community/community/discussions/39519#discussioncomment-4185035
- https://dev.to/rob_bos/how-github-actions-versioning-system-works-lec
